name: janus
channels:
  - rdkit
  - openbabel
  - defaults
dependencies:
  - openbabel=2.4.1
  - pandas=0.25.3
  - pip=19.3.1
  - python=3.6.9
  - rdkit=2019.03.1
  - pip:
    - git+https://github.com/sirimullalab/hypopt.git@master
    - joblib==0.14.1
    - numpy==1.17.0
    - pyparsing==2.4.7
    - xgboost==0.80
    - matplotlib==3.2.2
    - scikit-learn==0.20.0
    - tqdm