name: apple_tensorflow
channels:
  - rdkit
  - conda-forge
  - nodefaults
dependencies:
  # - rdkit::rdkit==2020.03.1
  - absl-py
  - astunparse
  - gast
  - google-pasta
  - grpcio
  - h5py
  - ipython
  - keras-preprocessing
  - numpy
  - opt_einsum
  - pip=20.2.3
  - protobuf
  - python-flatbuffers
  - python=3.8
  - scipy
  - tensorboard
  - tensorflow-estimator
  - termcolor
  - typeguard
  - typing_extensions
  - wheel
  - wrapt
  - rdkit
  - pandas
  - pytorch
  - selfies
  - pip:
    - -r requirements.txt
  
